[project]
name = "anki-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "genanki>=0.13.1",
    "webtypy>=0.1.7",
]

[dependency-groups]
dev = [
    "workers-py"
]
